---
driver:
  name: vcenter
  vcenter_username: 'administrator@vsphere.local'
  vcenter_password: 'Good4bye!'
  vcenter_host: '172.16.20.2'
  vcenter_disable_ssl_verify: true

provisioner:
  name: chef_zero
  sudo_command: sudo

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true
  username: administrator
  password: "Admini@"

platforms:
  - name: windows2012R2
    driver_config:
      targethost: 172.16.20.42
      template: windows2012R2
      datacenter: "Datacenter"

suites:
  - name: default
run_list:
  - recipe[vra-iaas-cookbook::default]
